# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

tasks:
  default:
    desc: Show help
    aliases: [h]
    silent: true
    cmds:
      - task -l --sort alphanumeric

  up:
    desc: up
    aliases: [start]
    cmds:
      - docker compose up -d --remove-orphans
  
  stop:
    desc: stop
    cmds:
      - docker compose stop -t 0

  restart:
    desc: Restart
    aliases: [r]
    cmds:
      - docker compose stop monstache
      - docker compose up -d monstache

  build:
    cmds:
      - docker compose build monstache

  golang:
    desc: Run a golang container
    aliases: [g]
    cmds:
      - >-
        docker run -it --rm
        --entrypoint /bin/sh
        -v ./monstache/go:/app
        -w /app
        --platform linux/amd64
        golang:1.20.4